---

- hosts: all
  tasks:
  

  - name: install packages
    package: #use either apt or yum
      name: 
      - "{{ git }}"
      - "{{ httpd }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"




