---

- hosts: all
  tasks:

  - name: update repo
    yum:
      update_cache: yes
    #when: ansible_distribution == "CentOS"

  - name: install-git
    yum:
      name: git
      state: latest
    #when: ansible_distibution == "CentOS" 

  - name: install-httpd
    yum:
      name: httpd
      state: latest
    #when: ansible_distribution == "CentOS"



