---

- hosts: all
  tasks:


  - name: install git and httpd
    yum:
      name: 
      - git
      - httpd
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"




