---

- hosts: all
  tasks:

  - name: update repo
    tags: always
    packages:
      update_cache: yes
      update_only: yes
  
  - name: copy files
    tags: files;centOS
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    


  
  - name: install-git
    tags: git
    yum:
      name: git
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install-httpd
    tags: httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"


  - name: start the httpd service (CentOS)
    tags: httpd-service
    service:
      name: httpd
      state: started
      enabled: yes # tells systemctl to enable the service after reboot
    when: ansible_distribution == "CentOS"

 
  - name: install unzip
    tags: unzip
    package:
      name: unzip


  - name: install terrform
    tags: terraform
    unarchive:
      src:  https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes #don't look in the files directory. 
      mode: 0755
      owner: root
      group: root

- name: instal ubuntu-packages (Ubunut)
  tags: ubuntu
  packages:
    - net-tools
  when: ansible_distribution == "Ubuntu"   





