---

- hosts: all
  tasks:

  - name: update repo
    tags: always
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution ==  "CentOS"

  - name: install-git
    tags: git
    yum:
      name: git
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install-httpd
    tags: httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"



